package com.cmfspay.ble.ble

/**
 * @author Python
 * @date 2018/9/28
 * @desc
 */
enum class AdvertiseStatus {

    ADVERTISE_NONE, ADVERTISE_SUCCESS, ADVERTISE_FAILED_ALREADY_STARTED, ADVERTISE_FAILED_DATA_TOO_LARGE, ADVERTISE_FAILED_FEATURE_UNSUPPORTED, ADVERTISE_FAILED_INTERNAL_ERROR, ADVERTISE_FAILED_TOO_MANY_ADVERTISERS,

}